### ISSUE TITLE
older reviews?

### ISSUE THREAD

**Issue by sanjaykmenon** [amrrs/itunesr#1]
very useful package! I see you're scraping it off the RSS feed.

Is there any way that it can be tuned to get older reviews? The earliest I can find are just around 3 weeks old.

**Comment by amrrs** [comment]
Thanks, Yes it parses the json feed. Have you tried with page number (the third argument) = 10? That's the oldest Apple provides. I've never found any other way so far.

**Comment by sanjaykmenon** [comment]
Yeah, i did! I've been trying to find an approach beyond the 10th page. 

Thanks anyways!
