### ISSUE TITLE
Date variable (it's more like a question then issue)

### ISSUE THREAD

**Issue by golovalastic** [amrrs/itunesr#7]
Hi! 

If I correctly understand dataframe included variable date of review in older version of itunesr. In current version dataframe includes 6 variables without a date. Is there way to use older version to scrap dataset with date variable?

Thank you!

**Comment by amrrs** [comment]
Hey @golovalastic Thanks for writing. I'm sorry that I had to make that change temporarily when the endpoints failed. 

Right now, the development version will give you what you want:

* Restart your R/RStudio
* devtools::install_github('amrrs/itunesr')

This should give you date. 

Please check and let me know. Also would be great to hear from you where are you using it.

**Comment by golovalastic** [comment]
Thank you very much! And also thousand thanks for working on this package.

**Comment by amrrs** [comment]
Glad it helped. Could you please let me know where are you using this? It'd be help me understand to make further packages in similar lines.
