### ISSUE TITLE
Error while getting reviews for Facebook app

### ISSUE THREAD

**Issue by ashgreat** [amrrs/itunesr#8]
I am trying to get reviews for the Facebook app from US app store. My code is as follows:
`colnames(getReviews(284882215,'us',n))`

Where `n` is incremented from 1 to 10. I get an error when n = 4 but not for other values:

`Error in names(reviews) <- c("Title", "Author_URL", "Author_Name", "App_Version",  : 
  'names' attribute [6] must be the same length as the vector [0]`

**Comment by amrrs** [comment]
Hi @ashgreat, Let me check if i can reproduce the error and come back.

**Comment by amrrs** [comment]
```
> df <- getReviews(284882215,'us',1)
> df <- getReviews(284882215,'us',4)
> df <- getReviews(284882215,'us',3)
> df <- getReviews(284882215,'us',4)
> df <- getReviews(284882215,'us',2)
> df <- getReviews(284882215,'us',4)
> names(df)
[1] "Title"       "Author_URL"  "Author_Name" "App_Version" "Rating"      "Review"     
> df <- getReviews(284882215,'us',3)
> names(df)
[1] "Title"       "Author_URL"  "Author_Name" "App_Version" "Rating"      "Review"    
```

I haven't got any error. Can you please check once again?

**Comment by amrrs** [comment]
Please open a new issue if the issue still exists!
